### ISSUE TITLE
Edit Transcript vs. QuoteMe Edit Lepiter Page

### ISSUE THREAD

**Issue by snrnyc** [seandenigris/Objective-Lepiter#15]
See also https://github.com/seandenigris/Quote-Me/issues/22

It seems confusing having both. Are they the same? Is there a case for keeping both?

In either case, the MA action should be disabled if there is none. Maybe the icon could include a + if not...

**Comment by seandenigris** [comment]
It seems confusing having both. Are they the same? Is there a case for keeping both?

**Comment by seandenigris** [comment]
Addressed by https://github.com/seandenigris/Objective-Lepiter/commit/2de22fa93a7a524d2f5accb2afd28a97ddbb6f56. Close for now.
